language: python

before_script:
- pip install tox

# test script
script:  tox
notifications:
  on_success: change
  on_failure: always

env:
  global:
  - GH3_RECORD_MODE='never'

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27 REQUESTS_VERSION=""
    - python: 3.4
      env: TOXENV=py34 REQUESTS_VERSION=""
    - python: 3.5
      env: TOXENV=py35 REQUESTS_VERSION=""
    - python: pypy
      env: TOXENV=pypy REQUESTS_VERSION=""
    - env: TOXENV=py27-flake8
    - env: TOXENV=py34-flake8
    - env: TOXENV=docstrings
    - env: TOXENV=notebooks
    - env: TOXENV=readme
    - env: TOXENV=docs
  fast_finish: true
  allow_failures:
  - env: TOXENV=docstrings
  - env: TOXENV=notebooks

sudo: false
